package models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Map;
import java.util.HashMap;
import java.time.Instant;

/**
 * Fraud Alert generated by the detection system
 */
public class FraudAlert {
    @JsonProperty("alert_id")
    private String alertId;
    
    @JsonProperty("user_id")
    private String userId;
    
    @JsonProperty("fraud_type")
    private String fraudType;
    
    @JsonProperty("severity")
    private String severity;
    
    @JsonProperty("confidence_score")
    private double confidenceScore;
    
    @JsonProperty("risk_score")
    private double riskScore;
    
    @JsonProperty("timestamp")
    private String timestamp;
    
    @JsonProperty("description")
    private String description;
    
    @JsonProperty("evidence")
    private Map<String, Object> evidence;
    
    @JsonProperty("status")
    private String status;

    public FraudAlert() {
        this.evidence = new HashMap<>();
        this.status = "open";
        this.timestamp = Instant.now().toString();
    }

    public FraudAlert(String userId, String fraudType, String severity, 
                     double confidenceScore, double riskScore, String description) {
        this();
        this.userId = userId;
        this.fraudType = fraudType;
        this.severity = severity;
        this.confidenceScore = confidenceScore;
        this.riskScore = riskScore;
        this.description = description;
    }

    // Getters and Setters
    public String getAlertId() { return alertId; }
    public void setAlertId(String alertId) { this.alertId = alertId; }

    public String getUserId() { return userId; }
    public void setUserId(String userId) { this.userId = userId; }

    public String getFraudType() { return fraudType; }
    public void setFraudType(String fraudType) { this.fraudType = fraudType; }

    public String getSeverity() { return severity; }
    public void setSeverity(String severity) { this.severity = severity; }

    public double getConfidenceScore() { return confidenceScore; }
    public void setConfidenceScore(double confidenceScore) { this.confidenceScore = confidenceScore; }

    public double getRiskScore() { return riskScore; }
    public void setRiskScore(double riskScore) { this.riskScore = riskScore; }

    public String getTimestamp() { return timestamp; }
    public void setTimestamp(String timestamp) { this.timestamp = timestamp; }

    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }

    public Map<String, Object> getEvidence() { return evidence; }
    public void setEvidence(Map<String, Object> evidence) { this.evidence = evidence; }

    public String getStatus() { return status; }
    public void setStatus(String status) { this.status = status; }
    
    // Additional fields and methods for enhanced fraud detection
    @JsonProperty("call_id")
    private String callId;
    
    @JsonProperty("location")
    private String location;
    
    @JsonProperty("composite_risk_score")
    private double compositeRiskScore;
    
    public String getCallId() { return callId; }
    public void setCallId(String callId) { this.callId = callId; }
    
    public String getLocation() { return location; }
    public void setLocation(String location) { this.location = location; }
    
    public double getCompositeRiskScore() { return compositeRiskScore; }
    public void setCompositeRiskScore(double compositeRiskScore) { this.compositeRiskScore = compositeRiskScore; }
    
    /**
     * Set timestamp with long value
     */
    public void setTimestamp(long timestamp) {
        this.timestamp = Instant.ofEpochMilli(timestamp).toString();
    }
    
    /**
     * Get timestamp as long value
     */
    public long getTimestampAsLong() {
        try {
            return Instant.parse(timestamp).toEpochMilli();
        } catch (Exception e) {
            return System.currentTimeMillis();
        }
    }

    @Override
    public String toString() {
        return "FraudAlert{" +
                "alertId='" + alertId + '\'' +
                ", userId='" + userId + '\'' +
                ", fraudType='" + fraudType + '\'' +
                ", severity='" + severity + '\'' +
                ", confidenceScore=" + confidenceScore +
                ", riskScore=" + riskScore +
                '}';
    }
}