"""
Shared data models for FraudGuard 360 system.
These models define the core data structures used across all services.
"""

from datetime import datetime
from typing import Optional, Dict, Any, List
from pydantic import BaseModel, Field
from enum import Enum


class CallType(str, Enum):
    """Types of calls in telecom systems"""
    VOICE = "voice"
    SMS = "sms"
    DATA = "data"
    VIDEO = "video"


class FraudType(str, Enum):
    """Types of fraud patterns detected"""
    SIM_BOX = "sim_box"
    SUBSCRIPTION_FRAUD = "subscription_fraud"
    PREMIUM_RATE_FRAUD = "premium_rate_fraud"
    ROAMING_FRAUD = "roaming_fraud"
    IDENTITY_THEFT = "identity_theft"
    ACCOUNT_TAKEOVER = "account_takeover"


class AlertSeverity(str, Enum):
    """Severity levels for fraud alerts"""
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class CDR(BaseModel):
    """Call Detail Record - the core event in our system"""
    id: str = Field(..., description="Unique identifier for the CDR")
    caller_id: str = Field(..., description="Calling party identifier")
    callee_id: str = Field(..., description="Called party identifier")
    call_type: CallType = Field(..., description="Type of call")
    start_time: datetime = Field(..., description="Call start timestamp")
    end_time: Optional[datetime] = Field(None, description="Call end timestamp")
    duration: Optional[int] = Field(None, description="Call duration in seconds")
    bytes_transmitted: Optional[int] = Field(None, description="Data transferred in bytes")
    location_caller: Optional[str] = Field(None, description="Caller location")
    location_callee: Optional[str] = Field(None, description="Callee location")
    tower_id: Optional[str] = Field(None, description="Cell tower ID")
    device_imei: Optional[str] = Field(None, description="Device IMEI")
    cost: Optional[float] = Field(None, description="Call cost")
    country_code: Optional[str] = Field(None, description="Country code")
    
    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat()
        }


class User(BaseModel):
    """User entity in the telecom system"""
    user_id: str = Field(..., description="Unique user identifier")
    phone_number: str = Field(..., description="Primary phone number")
    name: Optional[str] = Field(None, description="User name")
    email: Optional[str] = Field(None, description="User email")
    address: Optional[str] = Field(None, description="User address")
    registration_date: datetime = Field(..., description="Account registration date")
    account_status: str = Field(default="active", description="Account status")
    plan_type: Optional[str] = Field(None, description="Subscription plan type")
    risk_score: float = Field(default=0.0, description="Current risk score")
    
    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat()
        }


class Device(BaseModel):
    """Device entity in the system"""
    device_id: str = Field(..., description="Unique device identifier")
    imei: str = Field(..., description="Device IMEI")
    model: Optional[str] = Field(None, description="Device model")
    manufacturer: Optional[str] = Field(None, description="Device manufacturer")
    first_seen: datetime = Field(..., description="First time device was seen")
    last_seen: datetime = Field(..., description="Last time device was active")
    status: str = Field(default="active", description="Device status")
    
    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat()
        }


class Transaction(BaseModel):
    """Financial transaction entity"""
    transaction_id: str = Field(..., description="Unique transaction identifier")
    user_id: str = Field(..., description="User who made the transaction")
    amount: float = Field(..., description="Transaction amount")
    currency: str = Field(default="USD", description="Transaction currency")
    transaction_type: str = Field(..., description="Type of transaction")
    timestamp: datetime = Field(..., description="Transaction timestamp")
    merchant_id: Optional[str] = Field(None, description="Merchant identifier")
    location: Optional[str] = Field(None, description="Transaction location")
    
    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat()
        }


class FraudAlert(BaseModel):
    """Fraud alert generated by the system"""
    alert_id: str = Field(..., description="Unique alert identifier")
    user_id: str = Field(..., description="User associated with the alert")
    fraud_type: FraudType = Field(..., description="Type of fraud detected")
    severity: AlertSeverity = Field(..., description="Alert severity level")
    confidence_score: float = Field(..., description="Confidence in fraud detection (0-1)")
    risk_score: float = Field(..., description="Risk score assigned")
    timestamp: datetime = Field(..., description="Alert generation timestamp")
    description: str = Field(..., description="Human-readable alert description")
    evidence: Dict[str, Any] = Field(default_factory=dict, description="Supporting evidence")
    status: str = Field(default="open", description="Alert status")
    investigated_by: Optional[str] = Field(None, description="Investigator assigned")
    resolution: Optional[str] = Field(None, description="Alert resolution")
    
    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat()
        }


class NetworkRelationship(BaseModel):
    """Relationship between entities in the fraud network"""
    source_id: str = Field(..., description="Source entity ID")
    target_id: str = Field(..., description="Target entity ID")
    relationship_type: str = Field(..., description="Type of relationship")
    strength: float = Field(..., description="Relationship strength (0-1)")
    first_interaction: datetime = Field(..., description="First interaction timestamp")
    last_interaction: datetime = Field(..., description="Last interaction timestamp")
    interaction_count: int = Field(default=1, description="Number of interactions")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional metadata")
    
    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat()
        }


class FraudPattern(BaseModel):
    """Detected fraud pattern"""
    pattern_id: str = Field(..., description="Unique pattern identifier")
    pattern_type: FraudType = Field(..., description="Type of fraud pattern")
    entities_involved: List[str] = Field(..., description="List of entity IDs involved")
    confidence: float = Field(..., description="Pattern confidence score")
    timestamp: datetime = Field(..., description="Pattern detection timestamp")
    features: Dict[str, Any] = Field(default_factory=dict, description="Pattern features")
    
    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat()
        }


class ProcessingResult(BaseModel):
    """Result of processing a CDR through the fraud detection pipeline"""
    cdr_id: str = Field(..., description="CDR identifier")
    processing_timestamp: datetime = Field(..., description="Processing timestamp")
    alerts_generated: List[FraudAlert] = Field(default_factory=list, description="Generated alerts")
    risk_score: float = Field(..., description="Calculated risk score")
    patterns_detected: List[FraudPattern] = Field(default_factory=list, description="Detected patterns")
    processing_time_ms: int = Field(..., description="Processing time in milliseconds")
    
    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat()
        }